- name: Installing  packages in dynamic instance
  hosts: lunched_ec2_instances
  become: yes
  gather_facts: true

  tasks:
    - name: install the packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - httpd
      when: ansible_distribution == "Amazon"
    
    - name: Start the apache service
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Copy source code 
      synchronize:
        src: "{{ playbook_dir }}/../../"
        dest: "/opt/todo-app"
        delete: yes
        recursive: yes
        rsync_opts: 
          - "--exclude=.github"
          - "--exclude=ansible"