---
- name: luching of ec2 instance with security group
  hosts: localhost
  gather_facts: false

  tasks:
    - name: security group
      amazon.aws.ec2_security_group:
        name: test-ansible
        description: creating a security group
        vpc_id: vpc-04550d2e519f89bca
        rules:
            - proto: tcp
              from_port: 22
              to_port: 22
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 8080
              to_port: 8080
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 80
              to_port: 80
              cidr_ip: 0.0.0.0/0
            - proto: tcp
              from_port: 3001
              to_port: 3001
              cidr_ip: 0.0.0.0/0
        rules_egress:
            - proto: all
              cidr_ip: 0.0.0.0/0
      register: security_group
    
    - name: Lunch a ec2 instance
      amazon.aws.ec2_instance:
          name: Ansible-test-1
          key_name: new_key
          region: ap-south-1
          image_id: ami-062f0cc54dbfd8ef1
          instance_type: t2.micro
          security_group: "{{ security_group.group_id }}"       
          count: 1
      register: ec2

- name: Installing  packages in dynamic instance
  hosts: lunched_ec2_instances
  become: yes
  gather_facts: true

  tasks:
    - name: install the packages
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - httpd
      when: ansible_distribution == "Amazon"
    
    - name: Start the apache service
      service:
        name: httpd
        state: started
        enabled: yes
    
    - name: Copy source code 
      synchronize:
        src: "{{ playbook_dir }}/../../"
        dest: "/opt/todo-app"
        delete: yes
        recursive: yes
        rsync_opts: 
          - "--exclude=.github"
          - "--exclude=ansible"