name: provision of ec2 instance

on:
 push:
  branches:
   - master

jobs:
 provision_ec2:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout repo
     uses: actions/checkout@v2
          
   - name: Setup Python 3.x
     uses: actions/setup-python@v2
     with:
      python-version: "3.10"

   - name: Install dependenies
     run: |
      python -m pip install --upgrade pip
      pip install ansible boto3
      ansible-galaxy collection install amazon.aws
  
   - name: Configure Aws Credential
     uses: aws-actions/configure-aws-credentials@v1
     with:
       aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
       aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
       aws-region: ap-south-1 
   
   - name: Create SSH key file
     run: |
      mkdir -p ~/.ssh
      echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/ec2_key.pem
      chmod 600 ~/.ssh/ec2_key.pem
  
   - name: Debug SSH key
     run: ls -l ~/.ssh/ec2_key.pem

   - name: Run Ansible Playbook
     run: | 
      ansible-playbook ansible/playbooks/provision_and_configur_server.yml \
      -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem"

  #  - name: Run Ansible Playbook
  #    run: | 
  #     ansible-playbook ansible/playbooks/installing-app.yml \
  #     -e "ec2_ssh_key_path=~/.ssh/ec2_key.pem"
    

     env: 
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      EC2_SSH_PRIVATE_KEY: ~/.ssh/ec2_key.pem
      ANSIBLE_HOST_KEY_CHECKING: False


